pipeline {
    agent any

    stages {

        stage('Checkout') {
            steps {
                echo 'Code checked out from GitHub'
            }
        }

        stage('Build') {
            steps {
                dir('app') {
                    sh 'mvn clean package -DskipTests'
                }
            }
        }

        stage('Docker Build') {
            steps {
                dir('app') {
                    sh 'docker build -t kusumlohar03/springboot-chat-app:latest .'
                }
            }
        }

        stage('Docker Push') {
            steps {
                echo 'Docker push will be configured next'
            }
        }

        stage('Deploy') {
            steps {
                echo 'Deployment will be configured next'
            }
        }
    }
}
